
# This notebook was done as the second part to the third assignment of a machine learning class. This notebook contains codes using Support Vector Machines with Principal Component Analysis. The dataset was on 64x64 grayscale images doing facial recognition.




# Reference Links:
For data set in this notebook
https://drive.google.com/drive/folders/14Mi1I91iVQ13PG0SPjh9wN5NSNlBb3rb?usp=sharing




# Part A


In [1]:

import matplotlib.image as mpimg
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

label_df = pd.read_csv('C:\\Users\\KennoHead\\Desktop\\spring 2021\\4662\\Week 11\\Face-20210407T015356Z-001\\Face\\label.csv')
image_pixel_positions = []

for i in range (1, 4097, 1):
    image_pixel_positions.append (str(i))

Face_df = pd.DataFrame(columns = image_pixel_positions)



# Part B


In [2]:


file_path = 'C:\\Users\\KennoHead\\Desktop\\spring 2021\\4662\\Week 11\\Face-20210407T015356Z-001\\Face\\'

for i in range (0, 400, 1):
    current_image = mpimg.imread( file_path + str(i) + '.jpg')
    current_image_pixels_np_array = np.asarray(current_image)
    current_image_pixels_np_array = current_image_pixels_np_array.flatten()
    Face_df.loc[i] = current_image_pixels_np_array
    

Face_df['Label'] = label_df['Label']

print ('Done Processing!')


Done Processing!



# Part C


In [3]:

Face_Features = Face_df[ image_pixel_positions ]

Face_Labels = Face_df ['Label']

Face_Features_Scaled = preprocessing.scale(Face_Features)




# Part D



In [4]:

Face_Features_Training, Face_Features_Testing, Face_Labels_Training, Face_Labels_Testing = train_test_split (Face_Features_Scaled, Face_Labels, test_size =0.25, random_state = 5)




# Part E




In [5]:

from  sklearn.decomposition  import  PCA

k = 50
P_C_A = PCA(n_components = k)
Face_Features_Training_pca = P_C_A.fit_transform( Face_Features_Training )
Face_Features_Testing_pca = P_C_A.transform( Face_Features_Testing )



# Part F


In [6]:

from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

SVM_Classifier = svm.SVC( C = 1.0, kernel = 'rbf', gamma = 0.0005, random_state = 1)

SVM_Classifier.fit( Face_Features_Training_pca, Face_Labels_Training )
SVC_Predictions = SVM_Classifier.predict( Face_Features_Testing_pca )
SVC_Accuracy_Score = accuracy_score( Face_Labels_Testing, SVC_Predictions )
SVC_confusion_matrix = confusion_matrix( Face_Labels_Testing, SVC_Predictions )

print ( SVC_Accuracy_Score )
print( SVC_confusion_matrix )


0.91
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 4 0]
 [0 0 0 ... 0 0 1]]



# Part F Results
The accuracy score was 91.00%



# Part G


In [11]:

from sklearn.model_selection import GridSearchCV

C_Values = [ 0.1, 1, 10, 100, 1e3, 5e3, 1e4, 5e4, 1e5]
param_grid = dict( C = C_Values)

SVM_Classifier_CV = svm.SVC(kernel = 'rbf', gamma = 0.0005, random_state = 1)
PCA_CV = PCA(n_components = k)
Face_Features_Scaled_pca = PCA_CV.fit_transform ( Face_Features_Scaled )

grid = GridSearchCV(SVM_Classifier_CV, param_grid, cv=10, scoring='accuracy')
grid.fit( Face_Features_Scaled_pca, Face_Labels )

print(grid.best_params_)


{'C': 10}



# Part G Results
Based on the grid search cross validation run above, the best "C" value is 10.
